"""SQL Approval Schemas.

Pydantic models for SQL Human-in-the-Loop approval workflow.
These schemas handle the request/response cycle for SQL operation approval.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from infrastructure.integrations.db.sql_classifier import (
    ApprovalPolicy,
    DangerLevel,
    SQLOperationType,
)


class SQLApprovalStatus(str, Enum):
    """Status of an SQL approval request."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MODIFIED = "modified"  # User edited the SQL before approving
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class SQLApprovalAction(str, Enum):
    """Action taken by user on SQL approval request."""
    APPROVE = "approve"     # Execute SQL as-is
    EDIT = "edit"          # Modify SQL before executing
    REJECT = "reject"      # Cancel the operation


class SQLApprovalRequest(BaseModel):
    """Request for SQL operation approval.
    
    Sent to the frontend when a SQL operation requires user approval.
    """
    # Identification
    request_id: str = Field(..., description="Unique ID for this approval request")
    thread_id: str = Field(..., description="Thread ID where this request originated")
    run_id: Optional[str] = Field(None, description="Current run ID")
    
    # SQL Details
    generated_sql: str = Field(..., description="The SQL query generated by the agent")
    natural_language_query: str = Field(
        ..., description="Original natural language query from user"
    )
    
    # Classification
    operation_type: SQLOperationType = Field(..., description="Type of SQL operation")
    danger_level: DangerLevel = Field(..., description="Assessed danger level")
    affected_tables: List[str] = Field(
        default_factory=list, description="Tables affected by this query"
    )
    estimated_rows_affected: Optional[str] = Field(
        None, description="Estimate of rows affected"
    )
    
    # Safety
    approval_policy: ApprovalPolicy = Field(..., description="Required approval policy")
    warnings: List[str] = Field(
        default_factory=list, description="Safety warnings about this operation"
    )
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(
        None, description="When this approval request expires"
    )
    
    # Context for user
    explanation: str = Field(
        "", description="Agent's explanation of what this query does"
    )
    expected_result_description: Optional[str] = Field(
        None, description="What the user can expect from this query"
    )

    class Config:
        use_enum_values = True

    def to_user_message(self) -> str:
        """Generate a user-friendly message for the approval request."""
        lines = [
            "##SQL Operation Approval Required",
            "",
            f"**Your Request:** {self.natural_language_query}",
            "",
            "### Generated SQL",
            "```sql",
            self.generated_sql,
            "```",
            "",
            f"**Operation Type:** {self.operation_type}",
            f"**Danger Level:** {self.danger_level.upper()}",
            f"**Affected Tables:** {', '.join(self.affected_tables) or 'None detected'}",
        ]
        
        if self.estimated_rows_affected:
            lines.append(f"**Rows Affected:** {self.estimated_rows_affected}")
        
        if self.warnings:
            lines.append("")
            lines.append("###Warnings")
            for warning in self.warnings:
                lines.append(f"- {warning}")
        
        if self.explanation:
            lines.append("")
            lines.append("### Explanation")
            lines.append(self.explanation)
        
        lines.extend([
            "",
            "---",
            "**Actions:**",
            "- **approve** - Execute this SQL as-is",
            "- **edit** - Modify the SQL before executing",
            "- **reject** - Cancel this operation",
            "",
            "**Response Format:**",
            '```json',
            '{',
            '  "action": "approve|edit|reject",',
            '  "modified_sql": "..." (required if action is "edit"),',
            '  "reason": "..." (optional)',
            '}',
            '```',
        ])
        
        return "\n".join(lines)


class SQLApprovalResponse(BaseModel):
    """Response from user for SQL approval request.
    
    This model represents the user's decision on an SQL approval request.
    It should be passed as the resume value when using LangGraph's interrupt().
    
    Example usage with LangGraph:
        ```python
        # To approve as-is:
        graph.invoke(Command(resume={"action": "approve"}), config=config)
        
        # To edit before executing:
        graph.invoke(Command(resume={
            "action": "edit",
            "modified_sql": "SELECT * FROM users WHERE id = 123 LIMIT 10"
        }), config=config)
        
        # To reject:
        graph.invoke(Command(resume={
            "action": "reject",
            "reason": "Too dangerous"
        }), config=config)
        ```
    """
    # Decision action (required)
    action: SQLApprovalAction = Field(
        ..., 
        description="User's decision: approve, edit, or reject"
    )
    
    # Optional modifications (required if action is 'edit')
    modified_sql: Optional[str] = Field(
        None, 
        description="User-edited SQL (required if action is 'edit')"
    )
    
    # Optional feedback
    reason: Optional[str] = Field(
        None, 
        description="User's reason for rejection or modification"
    )
    
    # Legacy fields for backward compatibility
    request_id: Optional[str] = Field(
        None, 
        description="ID of the approval request (optional, for tracking)"
    )
    status: Optional[SQLApprovalStatus] = Field(
        None,
        description="Legacy status field (derived from action)"
    )
    responded_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of response"
    )
    user_id: Optional[str] = Field(
        None, 
        description="ID of user who responded"
    )

    class Config:
        use_enum_values = True

    def model_post_init(self, __context) -> None:
        """Validate that modified_sql is provided when action is 'edit'."""
        if self.action == SQLApprovalAction.EDIT and not self.modified_sql:
            raise ValueError("modified_sql is required when action is 'edit'")
        
        # Set legacy status based on action if not provided
        if not self.status:
            if self.action == SQLApprovalAction.APPROVE:
                self.status = SQLApprovalStatus.APPROVED
            elif self.action == SQLApprovalAction.EDIT:
                self.status = SQLApprovalStatus.MODIFIED
            elif self.action == SQLApprovalAction.REJECT:
                self.status = SQLApprovalStatus.REJECTED

    def get_final_sql(self, original_sql: str) -> Optional[str]:
        """Get the final SQL to execute.
        
        Returns:
            SQL to execute, or None if rejected/expired
        """
        if self.status in {SQLApprovalStatus.REJECTED, SQLApprovalStatus.EXPIRED, SQLApprovalStatus.CANCELLED}:
            return None
        
        if self.status == SQLApprovalStatus.MODIFIED and self.modified_sql:
            return self.modified_sql
        
        return original_sql


class SQLApprovalHistory(BaseModel):
    """History entry for SQL approval tracking."""
    request: SQLApprovalRequest
    response: Optional[SQLApprovalResponse] = None
    executed: bool = False
    execution_result: Optional[str] = None
    execution_error: Optional[str] = None
    execution_time_ms: Optional[float] = None

    def is_complete(self) -> bool:
        """Check if this approval cycle is complete."""
        return self.response is not None


class SQLExecutionResult(BaseModel):
    """Result of SQL execution after approval."""
    request_id: str
    success: bool
    sql_executed: str
    rows_affected: Optional[int] = None
    result_preview: Optional[str] = None  # First N rows for SELECT
    error_message: Optional[str] = None
    execution_time_ms: float
    executed_at: datetime = Field(default_factory=datetime.utcnow)


class PendingSQLApproval(BaseModel):
    """Model for storing pending SQL approval in agent state."""
    request: SQLApprovalRequest
    awaiting_response: bool = True
    retry_count: int = 0
    max_retries: int = 3

    def can_retry(self) -> bool:
        """Check if we can retry after modification."""
        return self.retry_count < self.max_retries
