[project]
name = "ai-study-roadmap"
version = "0.1.0"
description = "Required tools and libraries to fully build this."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "loguru",
  "rich",
  "pydantic",
  "python-dotenv",
  "requests",
  "langchain-core",
  "langchain-community",
  "langchain",
  "langgraph",
  "langchain-openai",
  "langsmith",
  "langchain-tavily",
  "fastapi[standard]",
  "streamlit",
  "langchain-qdrant",
  "qdrant-client",
  "pypdf",
  "sqlalchemy",
  "chonkie[semantic]",
  "rank_bm25",
  "cohere",
  "langchain-huggingface",
  "sentence_transformers",
  "psycopg2-binary",
  "alembic",
  "argon2-cffi",
  "pgvector",
  "redis",
  "langchain-redis",
  "pyjwt",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["backend*", "frontend*"]
