"""Alembic Migration Package for Database Schema Changes.

Commands:
    # Create a new migration
    alembic revision --autogenerate -m "description"
    
    # Apply all pending migrations
    alembic upgrade head
    
    # Rollback one migration
    alembic downgrade -1
    
    # Show current revision
    alembic current
    
    # Show migration history
    alembic history

Best Practices:
    1. Always review autogenerated migrations before applying
    2. Test migrations on a copy of production data
    3. Use meaningful migration messages
    4. Never modify applied migrations
"""
